name: build & push
on:
  workflow_call:
    inputs:
      IDE:
        required: true
        type: string
      IDE_SHORT:
        required: true
        type: string
      IDE_CODE:
        required: true
        type: string
      IDE_VERSION:
        required: false
        type: string
        default: "2021.3"
    secrets:
      username:
        required: true
      token:
        required: true
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./image
          build-args: |
            IDE=${{ inputs.IDE }}
            IDE_SHORT=${{ inputs.IDE_SHORT }}
            IDE_CODE=${{ inputs.IDE_CODE }}
            IDE_VERSION=${{ inputs.IDE_VERSION }}
          tags: |
            sunznx/jetbrains-indexer:${{ inputs.IDE_SHORT }}-${{ inputs.IDE_VERSION }}
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
